name: Main
permissions: write-all
on:
  workflow_dispatch:
    inputs:
      environment:
        description: '选择部署环境'  # 参数描述
        required: true             # 是否必填
        default: 'production'      # 默认值
        type: choice               # 参数类型（choice/string/boolean等）
        options:                   # 可选值（仅对 choice 类型有效）
          - 'production'
          - 'staging'
          - 'development'
      verbose_logging:
        description: '启用详细日志'
        required: false
        default: false
        type: boolean

jobs:
  build:
    name: build openwrt for tr3000
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Install dependence
        env:
          DEBIAN_FRONTEND: noninteractive
        run: sudo -E apt install build-essential clang flex bison g++ gawk gcc-multilib g++-multilib gettext git libncurses5-dev libssl-dev python3-setuptools rsync swig unzip zlib1g-dev file wget
        
      - name: Clone openwrt source code
        run: |
          git clone https://git.openwrt.org/openwrt/openwrt.git
          cd openwrt
          git branch -a
          git tag
          git checkout v24.10.0
          echo "src-git passwall_packages https://github.com/xiaorouji/openwrt-passwall-packages.git;main" >> "feeds.conf.default"
          echo "src-git passwall https://github.com/xiaorouji/openwrt-passwall.git;main" >> "feeds.conf.default"

      - name: Update the feeds
        run: |
          cd openwrt
          ./scripts/feeds update -a
          ./scripts/feeds install -a

      - name: Copy config file
        run: cp .config openwrt/

      - name: make download
        env:
          FORCE_UNSAFE_CONFIGURE: 1
        run: |
          cd openwrt
          make defconfig
          make download

      - name: make
        env:
          FORCE_UNSAFE_CONFIGURE: 1
        run: |
          cd openwrt
          make -j8
          
      - name: Rename the default bin
        run: |
          cd openwrt/bin/targets/mediatek/filogic/
          mv openwrt-mediatek-filogic-cudy_tr3000-v1-squashfs-sysupgrade.bin openwrt-mediatek-filogic-cudy_tr3000-v1-squashfs-sysupgrade-default.bin

      - name: apply and apply patch
        env:
          FORCE_UNSAFE_CONFIGURE: 1
        run: |
          cd openwrt
          git apply ../patches/112m.patch
          make -j8

      - name: Rename the 112M bin
        run: |
          cd openwrt/bin/targets/mediatek/filogic/
          mv openwrt-mediatek-filogic-cudy_tr3000-v1-squashfs-sysupgrade.bin openwrt-mediatek-filogic-cudy_tr3000-v1-squashfs-sysupgrade-112M.bin
        
      - name: zip the bin
        uses: montudor/action-zip@v1
        with:
          args: zip -qq -r openwrt-tr3000.zip openwrt/bin

      - name: Release and Upload
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          files: openwrt-tr3000.zip
          
      - name: Delete workflow runs
        uses: Mattraks/delete-workflow-runs@main
        with:
          retain_days: 0
          keep_minimum_runs: 2

      - name: Remove old Releases
        uses: dev-drprasad/delete-older-releases@master
        with:
          keep_latest: 3
          delete_tags: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
